App/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='ydelfos/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='ydelfos/logout.html'), name='logout'),
    path('', include('ydelfos.urls')),
]

ydelfos/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='ydelfos-home'),
    path('about/', views.about, name='ydelfos-about'),
    path('subjects/', views.subjects, name='ydelfos-subjects'),
    path('create-exam/', views.create_exam, name='ydelfos-create-exam'),
]

ydelfos/models.py
from django.db import models
from django.contrib.auth.models import User


class Subject(models.Model):

    name = models.CharField(max_length=30)
    professor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='PROFESOR')
    students = models.ManyToManyField(User, related_name='ALUMNOS')

    def __str__(self):

        return self.name

class Exam(models.Model):

    date = models.DateField()
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    description = models.TextField(blank=True)

    def __str__(self):

        return str(self.date)

ydelfos/forms.py
from django.db import models
from django import forms
from .models import Exam


class ExamForm(forms.ModelForm):

    class Meta:
        model = Exam
        fields = '__all__'

ydelfos/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import ExamForm
from .models import Subject, Exam


def home(request):
    return render(request, 'ydelfos/home.html')

def about(request):
    return render(request, 'ydelfos/about.html')

@login_required
def subjects(request):

    if request.user.groups.all()[0].name == 'Students':
        query = Subject.objects.filter(students = request.user)
    else:
        query = Subject.objects.filter(professor = request.user)

    print(query)


    data = []

    for subject in query:
        exam_query = Exam.objects.filter(subject=subject)
        aux = {}

        aux['name'] = subject
        aux['dates'] = exam_query
        aux['professor'] = subject.professor
        aux['students'] = subject.students.all()

        data.append(aux)
        
    
    print(data)

    # data = {
    #     item.name : [ item.professor, item.students.all() ] for item in zip(query, exams)
    # }

    context = {
        "data": data,
    }

    return render(request, 'ydelfos/subjects.html', context)

@login_required
def create_exam(request):

    form = ExamForm()
    if request.method == 'POST':
        form = ExamForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Examen añadido con éxito')
            return redirect('ydelfos-home')

    return render(request, 'ydelfos/create_exam.html', {'form': form})

ydelfos/templates/ydelfos/about.html
{% extends "ydelfos/base.html" %}
{% block content %}
  <h1>This is an example of an about page for Ydelfos</h1>
{% endblock %}

ydelfos/templates/ydelfos/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Ydelfos</title>
  </head>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'ydelfos/main.css' %}">

  <body>
   <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'ydelfos-home' %}">Django Ydelfos</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'ydelfos-home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'ydelfos-about' %}">About</a>
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'ydelfos-subjects' %}">Asignatuas</a>
                  {% ifequal user.groups.all.0.name 'Professors' %}
                    <a class="nav-item nav-link" href="{% url 'ydelfos-create-exam' %}">Crear</a>
                  {% endifequal %}
                {% endif %}
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">

                {% if user.is_authenticated %}
                <a class="navr-item nav-link" href="{% url 'logout' %}">Logout: {{ user }}</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                {% endif %}

              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>

ydelfos/templates/ydelfos/create_exam.html
{% extends "ydelfos/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method='post'>
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" value="xd">Submit</button>

    <script>
      $(function () {
        $("#id_date").datepicker({
          format:'dd/mm/yyyy',
        });
      });
    </script>
</form>

{% endblock %}

ydelfos/templates/ydelfos/home.html
{% extends "ydelfos/base.html" %}
{% block content %}
  <h1>Home page</h1>
{% endblock %}

ydelfos/templates/ydelfos/login.html
{% extends "ydelfos/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
    </div>
{% endblock content %}

ydelfos/templates/ydelfos/logout.html
{% extends "ydelfos/base.html" %}
{% block content %}
    <h2>Te has deslogeado</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Logear de nuevo</a>
        </small>
    </div>
{% endblock content %}

ydelfos/templates/ydelfos/subjects.html
{% extends "ydelfos/base.html" %}
{% block content %}

  <article class="media">
    {% for index in data %}
    <div class="content-section">
      <h1>{{ index.name }}</h1>
      <h4>{{ index.professor }}</h4>

      <ul>
      {% for exam in index.dates %}
        <li class="text-muted"> {{ exam.date }}: {{ exam.description }} </li>

      {% endfor %}
      </ul>

    </div>
    {% endfor %}
  </article>

{% endblock %}